//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBanwao.KarryKart.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int OfferID { get; set; }
        public string OfferName { get; set; }
        public string ImageLink { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
